language: node_js

node_js:
    - 4
    - 5
    - 6

notifications:
    email: false

cache:
    apt: true
    directories:
        - $HOME/.npm
        - $HOME/.cache/bower

addons:
    firefox: 39.0.3
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9

env:
    - CXX=g++-4.9

before_install:
    - npm install -g bower

before_script:
    - 'export DISPLAY=:99.0'
    - sh -e /etc/init.d/xvfb start
    - cd example && bower install --verbose && cd ..

script:
    - alias firefox-bin='firefox'
    - npm run server &
    - npm test
